"""Phase 4 API: stable risk prediction contract for the future ML5 model."""

from __future__ import annotations

from datetime import datetime

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

try:
    from PHASE_6.ML5 import predict
except ModuleNotFoundError:
    from pathlib import Path
    import sys

    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    from PHASE_6.ML5 import predict


app = FastAPI(title="Telecom Network Risk API")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://127.0.0.1:5173"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# 1. Create POST /network/predict-risk with a Pydantic request model.
class RiskPredictionRequest(BaseModel):
    grid_id: int = Field(ge=1, le=10000)
    avg_activity: float = Field(ge=0)
    activity_growth: float
    active_hours: int = Field(ge=0, le=24)
    peak_ratio: float = Field(ge=0)
    variability: float = Field(ge=0)
    internet_share: float = Field(ge=0, le=1)
    feature_timestamp: datetime


class RiskPredictionResponse(BaseModel):
    risk_score: float = Field(ge=0, le=1)
    risk_level: str
    model_version: str
    explanation_note: str
    feature_timestamp: datetime
    contributing_features: list[str] | None = None


# 3. Return risk_score, risk_level, model_version and feature_timestamp.
@app.post("/network/predict-risk", response_model=RiskPredictionResponse)
def predict_risk(request: RiskPredictionRequest) -> RiskPredictionResponse:
    # 2. Validate the incoming features against the ML2 schema.
    result = predict(request.model_dump())
    return RiskPredictionResponse(
        **result,
        explanation_note="Prediction generated by the trained ML3 Logistic Regression model.",
    )


# 4. Optionally return the top contributing feature names when the model supports it.
# 5. Retest the React prediction page without changing the frontend contract.
if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="127.0.0.1", port=8004)
